# Generated by Django 2.2.1 on 2019-05-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_room_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
